In [1]:
import pandas as pd

In [2]:
#import dataset
fighter_data=pd.read_csv('WW_clean_data_labelEncoded_Winner.csv')
fighter_data

,R_fighter,B_fighter,date,Winner,B_total_time_fought(seconds),B_total_rounds_fought,B_total_title_bouts,B_current_win_streak,B_current_lose_streak,B_longest_win_streak,...,R_Country_Iceland,R_Country_New Zealand,R_Country_Nigeria,R_Country_Palestine,R_Country_Russia,R_Country_USA,R_Country_brazil,R_Country_canada,R_Country_england,R_Country_ireland
0,Song Kenan,Max Griffin,3/20/2021,0,0.584908,28,0,0,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Leon Edwards,Belal Muhammad,3/13/2021,1,0.634631,34,0,0,1,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,Matthew Semelsberger,Jason Witt,3/13/2021,2,0.158087,3,0,0,1,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,Sean Brady,Jake Matthews,3/6/2021,2,0.623774,34,0,2,0,3,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,Belal Muhammad,Dhiego Lima,2/13/2021,2,0.548099,18,2,0,1,3,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,Diego Sanchez,Mickey Gall,3/2/2019,2,0.219519,8,0,3,0,3,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
109,Dwight Grant,Carlo Pedersoli Jr.,2/23/2019,2,0.330750,4,0,1,0,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
110,Vicente Luque,Bryan Barberena,2/17/2019,2,0.300875,19,0,1,0,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
111,Demian Maia,Lyman Good,2/2/2019,2,0.278988,6,0,1,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
112,Thiago Alves,Max Griffin,2/2/2019,2,0.605440,13,0,0,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
fighter_data=fighter_data.drop(['date'], axis=1)
fighter_data.head()

,R_fighter,B_fighter,Winner,B_total_time_fought(seconds),B_total_rounds_fought,B_total_title_bouts,B_current_win_streak,B_current_lose_streak,B_longest_win_streak,B_wins,...,R_Country_Iceland,R_Country_New Zealand,R_Country_Nigeria,R_Country_Palestine,R_Country_Russia,R_Country_USA,R_Country_brazil,R_Country_canada,R_Country_england,R_Country_ireland
0,Song Kenan,Max Griffin,0,0.584908,28,0,0,1,1,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Leon Edwards,Belal Muhammad,1,0.634631,34,0,0,1,4,9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,Matthew Semelsberger,Jason Witt,2,0.158087,3,0,0,1,1,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,Sean Brady,Jake Matthews,2,0.623774,34,0,2,0,3,10,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,Belal Muhammad,Dhiego Lima,2,0.548099,18,2,0,1,3,4,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
X=fighter_data.drop(['Winner', 'R_fighter', 'B_fighter'], axis=1)
y=fighter_data.Winner

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)

In [6]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs', random_state=1)

# Train the data
classifier.fit(X_train, y_train)

C:\Users\kimbe\anaconda3\envs\mlenv\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

LogisticRegression(random_state=1)

In [7]:
# Predict outcomes for test data set and save as a pandas DataFrame with the actual y_test data
predictions = classifier.predict(X_test)
pd.DataFrame({"Prediction": predictions, "Actual": y_test})

     Prediction  Actual
22            2       0
81            2       2
35            2       2
100           2       0
79            2       2
67            0       2
40            2       0
27            2       0
21            2       2
82            2       2
18            0       0
6             2       2
56            0       0
5             2       2
39            0       0
110           0       2
65            0       2
9             2       0
108           2       2
76            2       2
0             0       0
38            2       2
51            0       0
47            0       2
24            2       1
42            2       2
91            0       2
71            0       2
28            2       2

In [8]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, predictions)

0.5862068965517241