In [17]:
# Import our dependencies
import pandas as pd
from sklearn.preprocessing import StandardScaler,OneHotEncoder, minmax_scale

In [3]:
data_df = pd.read_csv("WW_clean_data_labelEncoded_Winner.csv")
data_df

,Unnamed: 0,R_fighter,B_fighter,date,Winner,B_total_time_fought(seconds),B_total_rounds_fought,B_total_title_bouts,B_current_win_streak,B_current_lose_streak,...,B_age,R_age,R_Stance_Orthodox,R_Stance_Southpaw,R_Stance_Switch,R_Stance_nan,B_Stance_Orthodox,B_Stance_Southpaw,B_Stance_Switch,B_Stance_nan
0,6,Song Kenan,Max Griffin,3/20/2021,0,809.531250,28,0,0,1,...,35,31,0,0,1,0,1,0,0,0
1,12,Leon Edwards,Belal Muhammad,3/13/2021,1,876.053223,34,0,0,1,...,32,29,1,0,0,0,0,1,0,0
2,20,Matthew Semelsberger,Jason Witt,3/13/2021,2,238.500000,3,0,0,1,...,34,28,1,0,0,0,1,0,0,0
3,36,Sean Brady,Jake Matthews,3/6/2021,2,861.528565,34,0,2,0,...,26,28,1,0,0,0,1,0,0,0
4,60,Belal Muhammad,Dhiego Lima,2/13/2021,2,760.285156,18,2,0,1,...,32,32,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,1022,Diego Sanchez,Mickey Gall,3/2/2019,2,320.687500,8,0,3,0,...,27,37,1,0,0,0,1,0,0,0
109,1027,Dwight Grant,Carlo Pedersoli Jr.,2/23/2019,2,469.500000,4,0,1,0,...,25,34,1,0,0,0,1,0,0,0
110,1045,Vicente Luque,Bryan Barberena,2/17/2019,2,429.531250,19,0,1,0,...,29,27,1,0,0,0,1,0,0,0
111,1062,Demian Maia,Lyman Good,2/2/2019,2,400.250000,6,0,1,0,...,33,41,0,0,1,0,1,0,0,0
112,1071,Thiago Alves,Max Griffin,2/2/2019,2,837.000000,13,0,0,1,...,33,35,1,0,0,0,0,0,1,0

In [5]:
# Create the OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit the encoder and produce encoded DataFrame
B_Country = pd.DataFrame(enc.fit_transform(data_df.B_Country.values.reshape(-1,1)))

# Rename encoded columns
B_Country.columns = enc.get_feature_names(['B_Country'])
B_Country

,B_Country_Argentina,B_Country_Australia,B_Country_Austria,B_Country_Brazil,B_Country_Canada,B_Country_China,B_Country_Denmark,B_Country_Iceland,B_Country_Jamaica,B_Country_Japan,...,B_Country_Northern Ireland,B_Country_Norway,B_Country_Palestine,B_Country_Russia,B_Country_Tunisia,B_Country_USA,B_Country_brazil,B_Country_england,B_Country_poland,B_Country_sweden
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
109,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
110,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
111,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
112,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [6]:
# Create the OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit the encoder and produce encoded DataFrame
R_Country = pd.DataFrame(enc.fit_transform(data_df.R_Country.values.reshape(-1,1)))

# Rename encoded columns
R_Country.columns = enc.get_feature_names(['R_Country'])
R_Country

,R_Country_Afghanistan,R_Country_Argentina,R_Country_Australia,R_Country_Austria,R_Country_Brazil,R_Country_China,R_Country_Denmark,R_Country_Germany,R_Country_Ghana,R_Country_Iceland,R_Country_New Zealand,R_Country_Nigeria,R_Country_Palestine,R_Country_Russia,R_Country_USA,R_Country_brazil,R_Country_canada,R_Country_england,R_Country_ireland
0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
109,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
110,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
111,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
112,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
#Merge one hot encoded country data
merged_df=data_df.join(B_Country)
merged_df2=merged_df.join(R_Country)

merged_df2.head()

,Unnamed: 0,R_fighter,B_fighter,date,Winner,B_total_time_fought(seconds),B_total_rounds_fought,B_total_title_bouts,B_current_win_streak,B_current_lose_streak,...,R_Country_Iceland,R_Country_New Zealand,R_Country_Nigeria,R_Country_Palestine,R_Country_Russia,R_Country_USA,R_Country_brazil,R_Country_canada,R_Country_england,R_Country_ireland
0,6,Song Kenan,Max Griffin,3/20/2021,0,809.531250,28,0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,12,Leon Edwards,Belal Muhammad,3/13/2021,1,876.053223,34,0,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,20,Matthew Semelsberger,Jason Witt,3/13/2021,2,238.500000,3,0,0,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,36,Sean Brady,Jake Matthews,3/6/2021,2,861.528565,34,0,2,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,60,Belal Muhammad,Dhiego Lima,2/13/2021,2,760.285156,18,2,0,1,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
merged_df2=merged_df2.drop(['Unnamed: 0'], axis=1)
merged_df2.head()

,R_fighter,B_fighter,date,Winner,B_total_time_fought(seconds),B_total_rounds_fought,B_total_title_bouts,B_current_win_streak,B_current_lose_streak,B_longest_win_streak,...,R_Country_Iceland,R_Country_New Zealand,R_Country_Nigeria,R_Country_Palestine,R_Country_Russia,R_Country_USA,R_Country_brazil,R_Country_canada,R_Country_england,R_Country_ireland
0,Song Kenan,Max Griffin,3/20/2021,0,809.531250,28,0,0,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Leon Edwards,Belal Muhammad,3/13/2021,1,876.053223,34,0,0,1,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,Matthew Semelsberger,Jason Witt,3/13/2021,2,238.500000,3,0,0,1,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,Sean Brady,Jake Matthews,3/6/2021,2,861.528565,34,0,2,0,3,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,Belal Muhammad,Dhiego Lima,2/13/2021,2,760.285156,18,2,0,1,3,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
from sklearn.preprocessing import minmax_scale

merged_df2[['B_total_time_fought(seconds)','R_total_time_fought(seconds)', 'B_Height_cms', 'R_Height_cms', 'B_Reach_cms', 'R_Reach_cms', 'B_Weight_lbs', 'R_Weight_lbs']] = minmax_scale(merged_df2[['B_total_time_fought(seconds)','R_total_time_fought(seconds)', 'B_Height_cms', 'R_Height_cms', 'B_Reach_cms', 'R_Reach_cms', 'B_Weight_lbs', 'R_Weight_lbs']])

In [24]:
merged_df2=merged_df2.drop(['B_Country', 'R_Country'], axis=1)
merged_df2.head()

,R_fighter,B_fighter,date,Winner,B_total_time_fought(seconds),B_total_rounds_fought,B_total_title_bouts,B_current_win_streak,B_current_lose_streak,B_longest_win_streak,...,R_Country_Iceland,R_Country_New Zealand,R_Country_Nigeria,R_Country_Palestine,R_Country_Russia,R_Country_USA,R_Country_brazil,R_Country_canada,R_Country_england,R_Country_ireland
0,Song Kenan,Max Griffin,3/20/2021,0,0.584908,28,0,0,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Leon Edwards,Belal Muhammad,3/13/2021,1,0.634631,34,0,0,1,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,Matthew Semelsberger,Jason Witt,3/13/2021,2,0.158087,3,0,0,1,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,Sean Brady,Jake Matthews,3/6/2021,2,0.623774,34,0,2,0,3,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,Belal Muhammad,Dhiego Lima,2/13/2021,2,0.548099,18,2,0,1,3,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
merged_df2.to_csv('WW_clean_data_labelEncoded_Winner.csv', index=False)